AWSTemplateFormatVersion: '2010-09-09'
        
Transform: AWS::Serverless-2016-10-31
Description: Dynamic Security Group Generator
Resources:
  Builder:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-awscli
        SemanticVersion: 1.16.238-build3
      # Parameters:
      #   SG: !Ref SG
      #   VpcId: !Ref VpcId
      #   IpRangeServiceName: EC2_INSTANCE_CONNECT
      